version: "3.9"

services:
  app:
    container_name: node-express-ts
    image: safwat/node-express-ts
    restart: always
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    # links:
    #   - db

  db:
    container_name: postgresql-on-docker
    image: postgresql
    volumes:
      - ./data:/data/db
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - .env
    # entrypoint: ["/usr/bin/mongod"]
    # command: "sudo mongod --dbpath /data/db"

  db-seeder:
    container_name: postgresql-seeder
    image: node:18-slim
    # working_dir: /usr/app
    volumes:
      - ./:/usr/app
    depends_on:
      - db
      # - app
    restart: no
    # environment:
    #   - NODE_ENV=development
    command: "yarn seed:dev -i"
    # command: "echo whyyyyyyyyyyyyyyyyyyyyyyy"
