FROM node:18-alpine

ENV NODE_ENV=development
ENV DEBUG=express:* 

# CREATE APP DIRECTORY
WORKDIR /usr/app

# Copy packagesjson and yarn lock
COPY ./package.json .
COPY ./yarn.lock .

# Install app dependencies
RUN yarn

# Bundle app source
COPY . .

EXPOSE 4000

CMD ["yarn", "start:dev"]