FROM node:18-alpine

# CREATE APP DIRECTORY
WORKDIR /app

# Install app dependencies
COPY package.json .
COPY yarn.lock .

# Install app dependencies
RUN yarn

# Bundle app source
COPY . .

EXPOSE 8000

ENV NODE_ENV=development
ENV DEBUG=express:* 

CMD yarn start:dev